agent:
  tools_file: tools.py
  entry_file: agent.py
  system_prompt_var: SYSTEM_PROMPT
  get_tools_func: get_tools
  handle_message_func: handle_message

backend:
  type: sqlite
  db_engine_attr: db_engine

external_tools:
  - name: slack_post_message
    description: "Post a message to a Slack channel"
    mock_response: "Message posted successfully"
    parameters:
      channel_id:
        type: string
        description: "The Slack channel ID to post to"
        required: true
      text:
        type: string
        description: "The message text to post"
        required: true

entities:
  - name: order
    table: orders
    description: "Customer order information"
    fields:
      id:
        type: string
        description: "Order ID (e.g., ORD-001)"
      customer_id:
        type: string
        description: "Customer ID who placed the order"
      price:
        type: number
        min: 0
        description: "Order total price in dollars"
      status:
        type: string
        enum: [pending, processing, shipped, delivered, cancelled]
        description: "Current order status"
      delivered_date_days_ago:
        type: integer
        min: 0
        description: "Days since order was delivered (0 if not delivered)"

  - name: customer
    table: customers
    description: "Customer information"
    fields:
      id:
        type: string
        description: "Customer ID (e.g., CUST-001)"
      tier:
        type: string
        enum: [standard, gold, platinum]
        description: "Customer tier level"
      name:
        type: string
        description: "Customer name"
      email:
        type: string
        format: email
        description: "Customer email address"
